# Generated by Django 3.1 on 2020-08-18 22:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('backend', '0001_initial'), ('backend', '0002_auto_20200818_1603'), ('backend', '0003_auto_20200818_2108')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], max_length=150)),
                ('accepted_at', models.DateField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category')),
                ('tags', models.ManyToManyField(to='backend.Tag')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'social links',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.business')),
                ('app_office_number', models.CharField(blank=True, help_text='App/Office number', max_length=10)),
                ('street_number', models.SmallIntegerField()),
                ('street_type', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=200)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(default='Montreal', max_length=200)),
                ('province', models.CharField(default='QC', max_length=100)),
                ('postal_code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('opening_time', models.TimeField(max_length=100)),
                ('closing_time', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.business')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
            ],
            options={
                'ordering': ('day', 'opening_time'),
                'unique_together': {('day', 'opening_time', 'opening_time')},
                'verbose_name_plural': 'opening hours',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message="Format: '222 333 5555','222-333-5555','+1 222-333-5555'", regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-](\\d{3})[\\s.-](\\d{4})$')])),
                ('type', models.CharField(choices=[('tel', 'Telephone'), ('fax', 'Fax')], max_length=25)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.business')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'social links',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.business')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'social links',
            },
        ),
    ]
