# Generated by Django 3.0 on 2020-09-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="tags",
            field=models.ManyToManyField(null=True, to="backend.Tag"),
        ),
    ]
