# Generated by Django 3.1.1 on 2020-10-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_auto_20201010_2106"),
    ]

    operations = [
        migrations.AddField(
            model_name="openinghour",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="openinghour",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="openinghour",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
