# Generated by Django 3.1 on 2020-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_auto_20200822_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="tags",
            field=models.ManyToManyField(null=True, to="backend.Tag"),
        ),
    ]
