# Generated by Django 3.1 on 2020-09-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_auto_20200901_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="tags",
            field=models.ManyToManyField(blank=True, to="backend.Tag"),
        ),
    ]
