# Generated by Django 3.1.1 on 2020-09-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_auto_20200920_0111"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttype",
            options={"verbose_name_plural": "payment types"},
        ),
        migrations.AlterField(
            model_name="business",
            name="description",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="name",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("cash", "Cash"),
                    ("crypto", "Crypto"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
