# Generated by Django 3.1 on 2020-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200819_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='extension',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
