# Generated by Django 3.1 on 2020-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_auto_20200825_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("refused", "Refused"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="tags",
            field=models.ManyToManyField(to="backend.Tag"),
        ),
    ]
