# Generated by Django 3.1.1 on 2020-09-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_auto_20200920_2334"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="openinghour",
            unique_together={("day", "opening_time", "closing_time")},
        ),
    ]
