# Generated by Django 3.1.1 on 2020-10-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_business_last_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="slogan_en",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="slogan_fr",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
