# Generated by Django 3.1.1 on 2020-11-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.category",
            ),
        ),
    ]
