# Generated by Django 3.1.1 on 2020-12-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_accept_empty_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
