# Generated by Django 3.1.4 on 2021-01-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_suggestion"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Suggestion", new_name="BusinessSuggestion",
        ),
    ]
