# Generated by Django 3.1.4 on 2021-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_auto_20210103_2332"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssuggestion",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
