# Generated by Django 3.1 on 2020-08-18 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.business')),
                ('app_office_number', models.CharField(blank=True, help_text='App/Office number', max_length=10)),
                ('street_number', models.SmallIntegerField()),
                ('street_type', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=200)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(default='Montreal', max_length=200)),
                ('province', models.CharField(default='QC', max_length=100)),
                ('postal_code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'social links'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ('day', 'opening_time'), 'verbose_name_plural': 'opening hours'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name_plural': 'social links'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'social links'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='business',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phone',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.business'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
    ]
