# Generated by Django 3.1 on 2020-08-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200818_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='accepted_at',
            field=models.DateField(null=True),
        ),
    ]
