# Generated by Django 3.1 on 2020-08-19 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200818_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Format: '+1-514-111-1111,514-111-1111,+1 514 111 1111,514-111-1111,514 111 1111,111-1111,111 1111'", regex='(\\+\\d{1})?((\\-|\\s)\\d{3})?((\\-|\\s)\\d{3})((\\-|\\s)\\d{4})$')]),
        ),
    ]
